### PR TITLE
Python 3.7 compatibility

### LINKED ISSUE #93: Python 3.7 compatibility
This is related to blockdiag/seqdiag#24, once I get seqdiag to compile with Python 3.7 I get a failure in its test suite:

```
ERROR: test_setup_inline_svg_is_true_but_format_isnt_svg (test_rst_directives.TestRstDirectives)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/myitertools.py", line 41, in stepslice
    next(iterable)
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builddir/build/BUILD/python3-python-seqdiag-0.9.5-14.fc29/src/seqdiag/tests/test_rst_directives.py", line 166, in test_setup_inline_svg_is_true_but_format_isnt_svg
    doctree = publish_doctree(text)
  File "/usr/lib/python3.7/site-packages/docutils/core.py", line 481, in publish_doctree
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python3.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/rst/directives.py", line 54, in decorator
    return fn(*args)
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/rst/directives.py", line 178, in run
    results[0] = self.node2image(node, diagram)
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/rst/directives.py", line 254, in node2image
    drawer.save()
  File "/usr/lib/python3.7/site-packages/blockdiag/drawer.py", line 187, in save
    return self.drawer.save(self.filename, size, self.format)
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/filters/linejump.py", line 181, in save
    self._run()
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/filters/linejump.py", line 108, in _run
    method(self.target, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/png.py", line 217, in line
    self.dashed_line(xy, **kwargs)
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/png.py", line 230, in dashed_line
    for subline in dashize_line(line, cycle):
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/png.py", line 61, in dashize_line
    for y1, y2 in istep(n for n in r):
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/myitertools.py", line 22, in istep
    yield [next(iterable) for _ in range(step)]
  File "/usr/lib/python3.7/site-packages/blockdiag/utils/myitertools.py", line 22, in <listcomp>
    yield [next(iterable) for _ in range(step)]
  File "/usr/lib/python3.7/site-packages/blockdiag/imagedraw/png.py", line 61, in <genexpr>
    for y1, y2 in istep(n for n in r):
RuntimeError: generator raised StopIteration
----------------------------------------------------------------------
Ran 88 tests in 0.964s
FAILED (errors=1, skipped=33)
```

Looking at `myitertools.py` and [PEP 479](https://www.python.org/dev/peps/pep-0479/) I'm not sure what the best course of action is to fix this.

### PR DESCRIPTION
**Pull request by dridi**
See PEP 479 for the breaking changes around iterators, based on
@serhiy-storchaka's suggestions for myitertools.py changes.

Fixes #93 

Best viewed with `--ignore-all-space`: https://github.com/dridi/blockdiag/commit/f68ac237c974c5e4de3ddd0883f911c9bfef8569?w=1

### CODE REVIEW

**Review by serhiy-storchaka — APPROVED** [review]
LGTM except the poor name of 'iterable'. This is not a general iterable, but an iterator.

**Comment by dridi** [comment]
@serhiy-storchaka I don't disagree, but kept the changes to a minimum and left it as-is.

**Comment by ViktorHaag** [comment]
What can we do to help getting this merged and released quickly?

**Comment by tk0miya** [comment]
Sorry for late. just merged.
Thank you for all :-)

**Pull request merged**
