### PR TITLE
fix(svg): sanitize URL for invalid files

### LINKED ISSUE #147: file existence disclosure using svg renderer
Using the **svg renderer**, file existence can be disclosed. This is especially relevant if running blockdiag on a server.

e.g.

```
blockdiag {
A [label = "not exists", background="/etc/test"];
B [label = "exists", background="/etc/passwd"];
}
```

does show:
Screenshot 2021-08-16 at 17 07 51

Relevant code in https://github.com/blockdiag/blockdiag/blob/master/src/blockdiag/imagedraw/svg.py#L250

### PR DESCRIPTION
**Pull request by nejch**
Closes #147. This is built on top of #149 because the current master isn't building/passing tests properly. I can rebase after the other PR gets merged if needed.

Note that this only sanitizes URLs on parse errors when serving via SVG to prevent arbitrary non-image file disclosure.

It does not however prevent people from rendering arbitrary _valid_ images using blockdiag. Preventing that would also potentially break existing workflows, so I think a more general approach that checks for path traversal might be needed as it might affect other renderers. Perhaps with a global `--safe` flag?

(This would also then have to be passed to blockdiag from consumers such as kroki. /cc @Mogztter I know you've done some work with `KROKI_SAFE_MODE`, so I'd love to hear your opinion as well).

/cc @bufferoverflow

### CODE REVIEW

**Comment by tk0miya** [comment]
Thanks!

**Comment by bufferoverflow** [comment]
thank you @tk0miya ! Could you maybe push a new release containing this fix to https://pypi.org/project/blockdiag/ ?

**Comment by tk0miya** [comment]
I'll do it later (maybe tomorrow or next day). Now I'm working to update other *diag repositories. They should also be updated until releasing a new package.

**Comment by ggrossetie** [comment]
Great work @nejch 🎉 

> Preventing that would also potentially break existing workflows, so I think a more general approach that checks for path traversal might be needed as it might affect other renderers. Perhaps with a global --safe flag?

Could be a good addition.
In Kroki, we are using security levels in order to restrict access to files on the file system and on the network:
The `--safe` could disable reading files outside of the "working directory" (and from the network) and `--secure` could disable completely reading files the file system or from the network. 
If we want to be backward compatible then by default we could run in "unsafe" mode (i.e., no restrictions).

If we want a more fine-grained configuration then we could introduce the concept of "allow list" to allow reading from paths and URLs.

Thanks @tk0miya for taking the time to review and merge this pull request 🙇🏻

**Pull request merged**
